### CV{.mb-3}

**Senior Postdoctoral Researcher**  
*Mediterranean Institute for Advanced Studies (IMEDEA, UIB-CSIC),*  jointly affiliated with the Spanish National Research Council (CSIC) and the University of the Balearic Islands (UIB), Spain
<br>**05/2025 – present**

**Research Associate**  
*University of Western Australia (UWA), Australia*  
**01/2022 – 01/2025**

**Guest Postdoctoral Researcher**  
*Leibniz Institute for Baltic Sea Research (IOW), Germany*  
**01/2021 – 12/2021**

**Postdoctoral Researcher**  
*Leibniz Institute for Baltic Sea Research (IOW), Germany*  
**07/2020 – 12/2020**

**Ph.D. in Physical Oceanography**  
*Leibniz Institute for Baltic Sea Research (IOW), Universität Rostock, Germany*  
**01/2017 – 11/2020**  
Thesis: [*Frontal instability and energy dissipation in submesoscale fronts*](https://rosdok.uni-rostock.de/file/rosdok_disshab_0000002420/rosdok_derivate_0000096534/Peng_Dissertation_2021.pdf) <br> 
Supervisor: [PD Dr. Lars Umlauf](https://www.iow.de/lars-umlauf-en.html) (Editor, Journal of Geophysical Research - Oceans)  

**Research Assistant**  
*National Cheng Kung University, Taiwan (ROC)*  
**03/2016 – 12/2016**

**Research Assistant**  
*National Taiwan Ocean University, Taiwan (ROC)*  
**10/2014 – 02/2015**

**M.Sc.**  
*National Taiwan Ocean University, Taiwan (ROC)*  
**09/2013 – 10/2014**  
Thesis: *A study on coastal sea surface temperature drop after typhoon passage* 
Supervisor: Prof. Dong-Jiing Doong (now at National Cheng Kung University)

**B.Sc.**  
*National Taiwan Ocean University, Taiwan (ROC)*  
**09/2009 – 07/2013**

### Awards{.mb-3}

**2026:**
[*First Prize Outstanding Young Scientist Award (OYSA)*](https://iwmo.net/iwmo-2026/) at 16th International Workshop on Modeling the Ocean, Palma, Balearic Island, June 2-5

**2022:**
*UWA Research Collaboration Award*, Australia

**2022:** 
*UA-DAAD Australia-Germany Joint Research Award*, Australia

**2021:** 
[*American Geophysical Union (AGU) Outstanding Reviewer Award*](https://www.uwa.edu.au/news/article/2022/august/awards-and-achievements), for Geophysical Research Letters, nominated by Prof. Caitlin Whalen from University of Washington

**2020:**
*Ph.D. thesis awarded magna cum laude (with Great Distinction)* by Universität Rostock

**2014:**
*DAAD Summer Institute Student Internship Program Award*

**2013:**
*Taiwanese Exchange Student Scholarship Award*

### Invited Presentations{.mb-3}

**03/2025:**
[*Frontiers in Surface Mixed Layer Dynamics and Turbulence*](https://www.ihos.ncu.edu.tw/p/404-1004-5537.php?Lang=zh-tw), Seminar, Institute of Hydrological and Oceanic Sciences, National Central University, Taiwan (ROC)

**12/2024:** 
*Submesoscale Fronts and Diurnal Warm Layers*, The 2nd Annual Conference of Marine System, Sun Yat-sen University, Zhuhai, China

**11/2024:** 
[*Submesoscale Fronts and Diurnal Warm Layers*](https://ocean.nsysu.edu.tw/p/406-1271-341764,r3555.php?Lang=zh-tw), College Seminar, College of Marine Sciences, National Sun Yat-sen University, Taiwan (ROC)
 
**05/2024:**
[*Symmetric Instability and Turbulence under Theoretically Unfavorable Conditions*](https://marine.sysu.edu.cn/event/10035), 
The 21st Pacific-Asian Marginal Seas (PAMS) Meeting, Zhuhai, China

**02/2023:**
[*Diurnal Variability of Frontal Dynamics, Instability, and Energy Dissipation*](https://www.conferences.uni-hamburg.de/event/281/), Eddy-Wave Meeting, University of Hamburg, Germany
 
**04/2022:**
[*Submesoscale Dynamics and Turbulence under Theoretically-Unfavorable Conditions for Symmetric Instability*](https://www.geomar.de/en/service/veranstaltungen/wiss-veranstaltungen/details?tx_news_pi1%5Baction%5D=detail&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Bnews%5D=8411&cHash=71489d3d7ee4ecc8a975b5e9db33d4a2), Ocean Circulation and Climate Dynamics Colloquium (GEOMAR), Germany, online

**04/2022:** 
*Submesoscale Dynamics and Turbulence under Theoretically-Unfavorable*, Conditions for Symmetric InstabilityMixing Seminar, University of Southampton, UK

### Teaching{.mb-3}

***Physical Oceanography (Master level) -- Guest Lecturer***<br>
Ocean Graduate School, University of Western Australia, Australia<br> 
**10/2022**

***Marine Turbulence (Master level)- Teaching Assistant***<br> 
Physics department, Universität Rostock, Germany<br> 
**04-09/2019**

***Hydrodynamics (Bachelor level) - Teaching Assistant***<br> 
Physics department, Universität Rostock, Germany<br> 
**10/2018–03/2019**

***MATLAB (Bachelor level) - Teaching Assistant***<br> 
Department of Marine Environmental Informatics, National Taiwan Ocean University, Taiwan (ROC)<br> 
**02/2013–07/2013**

### Research Cruises{.mb-3}
<h4>(98 days in total)</h4>

**06/2024:** 
[R/V Solander, Australian Northwest Shelf](https://research-repository.uwa.edu.au/en/datasets/swotmooringtemperaturepressure/), University of Western Australia, 7 days, co-PI 

**04-05/2023:**
[R/V Solander, Australian Northwest Shelf](https://research-repository.uwa.edu.au/en/datasets/swotmooringvelocity/), University of Western Australia, 28 days, co-PI 

**09/2019:** 
[R/V Alice, Bornö Fjord](https://nbiocean.bitbucket.io/bornoe2019b/), University of Copenhagen, 7 days 

**02/2019:** 
[R/V Electra, Northern Baltic Sea](https://os.copernicus.org/articles/19/1809/2023/#section12), Stockholm University, 14 days 

**11-12/2018:** 
R/V EMB, Central Baltic Sea, German Research Foundation (DFG), 21 days

**10-11/2017:** 
[R/V EMB, Central Baltic Sea](https://www.seanoe.org/data/01010/112214/), German Research Foundation (DFG), 21 days 

**Instruments used:** 
Microstructure Turbulence Profilers, ship-board and moored ADCPs, drifter, autonomous gliders and wirewalkers, as well as standard oceanographic instruments.

**Methods:** 
Tow-yo profiling mode with turbulence profilers to measure submesoscale fronts